// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddServer'](arg1, arg2, arg3);
}

export function GetDocsFromServer(arg1, arg2) {
  return window['go']['main']['App']['GetDocsFromServer'](arg1, arg2);
}

export function GetInfoFromServer(arg1, arg2) {
  return window['go']['main']['App']['GetInfoFromServer'](arg1, arg2);
}

export function GetPathsFromServer(arg1, arg2) {
  return window['go']['main']['App']['GetPathsFromServer'](arg1, arg2);
}

export function LoadAppConfig() {
  return window['go']['main']['App']['LoadAppConfig']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SavePath(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SavePath'](arg1, arg2, arg3, arg4);
}
