// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddServer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetDocsFromServer(arg1:string,arg2:string):Promise<main.Docs>;

export function GetInfoFromServer(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetPathsFromServer(arg1:string,arg2:string):Promise<main.PathsResponse>;

export function LoadAppConfig():Promise<void>;

export function LoadConfig():Promise<main.AppConfig>;

export function SavePath(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;
